import type {
  AppState,
  CompletionSource,
  Condition,
  Favorite,
  GradeStatus,
  Inquiry,
  Listing,
  ListingStatus,
  MeetupMethod,
  Message,
  Sport,
  Trade,
  TransactionType,
  User,
} from '../types'
import { placeholderImage } from './images'

export const demoUsers: User[] = [
  { id: 'user-landers', loginId: 'landers', nickname: '랜더스팬' },
  { id: 'user-minsu', loginId: 'minsu', nickname: '홈런왕민수' },
  { id: 'user-court', loginId: 'courtstar', nickname: '코트위의별' },
  { id: 'user-goal', loginId: 'goalnet', nickname: '골망지기' },
  { id: 'user-yujin', loginId: 'yujin', nickname: '컬렉터유진' },
]

type Draft = {
  id: string
  ownerId: string
  title: string
  sport: Sport
  player: string
  manufacturer?: string
  setName?: string
  year?: string
  cardNumber?: string
  parallel?: string
  condition: Condition
  conditionNote: string
  gradeStatus?: GradeStatus
  grader?: string
  grade?: string
  certNumber?: string
  transactionType: TransactionType
  askingPrice: number | null
  tradeWish?: string
  method: MeetupMethod
  meetupArea?: string
  shippingFee: number | null
  status?: ListingStatus
  completionSource?: CompletionSource | null
  day: number
  hour: number
}

function at(day: number, hour: number, minute = 0): string {
  return new Date(Date.UTC(2026, 9, day, hour - 9, minute, 0)).toISOString()
}

const drafts: Draft[] = [
  {
    id: 'listing-01',
    ownerId: 'user-landers',
    title: '2024 이정후 루키 오토 리프랙터',
    sport: 'baseball',
    player: '이정후',
    manufacturer: 'Topps',
    setName: 'Chrome',
    year: '2024',
    cardNumber: 'JH-RA',
    parallel: 'Refractor Auto',
    condition: 'near_mint',
    conditionNote: '모서리 화이트닝은 없고 표면 스크래치도 눈에 띄지 않습니다. 슬랩 케이스 모서리에 약한 잔기스만 있습니다.',
    gradeStatus: 'graded',
    grader: 'PSA',
    grade: '10',
    certNumber: '100245781',
    transactionType: 'sale',
    askingPrice: 185000,
    method: 'both',
    meetupArea: '마포구',
    shippingFee: 3500,
    day: 6,
    hour: 11,
  },
  {
    id: 'listing-02',
    ownerId: 'user-landers',
    title: '2019 류현진 올스타 카드',
    sport: 'baseball',
    player: '류현진',
    manufacturer: 'Topps',
    setName: 'Update',
    year: '2019',
    cardNumber: '0072',
    condition: 'good',
    conditionNote: '좌상단 모서리에 작은 화이트닝이 있고 표면은 대체로 깨끗합니다. 탑로더에 보관 중입니다.',
    transactionType: 'sale',
    askingPrice: 92000,
    method: 'delivery',
    shippingFee: 3000,
    status: 'reserved',
    day: 4,
    hour: 15,
  },
  {
    id: 'listing-03',
    ownerId: 'user-minsu',
    title: '2023 김하성 보먼 1st',
    sport: 'baseball',
    player: '김하성',
    manufacturer: 'Bowman',
    setName: 'Chrome',
    year: '2023',
    cardNumber: '0048',
    parallel: 'Refractor',
    condition: 'near_mint',
    conditionNote: '센터링이 약간 위로 치우쳤고 모서리와 표면은 깨끗합니다. 슬리브와 탑로더에 넣어 두었습니다.',
    transactionType: 'trade',
    askingPrice: null,
    tradeWish: '같은 시기 김하성 오토나 이정후 루키 베이스 카드와 교환하고 싶습니다.',
    method: 'meetup',
    meetupArea: '송파구',
    shippingFee: null,
    day: 5,
    hour: 18,
  },
  {
    id: 'listing-04',
    ownerId: 'user-landers',
    title: '2024 오타니 쇼헤이 리프랙터',
    sport: 'baseball',
    player: '오타니 쇼헤이',
    manufacturer: 'Topps',
    setName: 'Chrome',
    year: '2024',
    cardNumber: '1',
    parallel: 'Refractor',
    condition: 'near_mint',
    conditionNote: '슬랩 안쪽 카드 모서리는 날카롭고 홀로그램 표면 스크래치는 보이지 않습니다. 케이스 하단 모서리만 살짝 닿았습니다.',
    gradeStatus: 'graded',
    grader: 'BGS',
    grade: '9.5',
    certNumber: '0014288766',
    transactionType: 'sale',
    askingPrice: 240000,
    method: 'delivery',
    shippingFee: 4000,
    day: 5,
    hour: 12,
  },
  {
    id: 'listing-05',
    ownerId: 'user-landers',
    title: '2020 추신수 베이스 카드 나눔',
    sport: 'baseball',
    player: '추신수',
    manufacturer: 'Topps',
    setName: 'Series 2',
    year: '2020',
    cardNumber: '150',
    condition: 'played',
    conditionNote: '가장자리 화이트닝이 있고 표면에도 잔기스가 있습니다. 수집용 여분으로 나눔합니다.',
    transactionType: 'giveaway',
    askingPrice: 0,
    method: 'delivery',
    shippingFee: 0,
    day: 3,
    hour: 10,
  },
  {
    id: 'listing-06',
    ownerId: 'user-landers',
    title: '1998 박찬호 플레어 카드',
    sport: 'baseball',
    player: '박찬호',
    manufacturer: 'Fleer',
    setName: 'Tradition',
    year: '1998',
    cardNumber: '12',
    condition: 'good',
    conditionNote: '빈티지 카드라 모서리에 사용감이 있습니다. 표면 주름은 없고 슬랩 라벨은 등록자가 입력한 등급입니다.',
    gradeStatus: 'graded',
    grader: 'PSA',
    grade: '8',
    certNumber: '8822104',
    transactionType: 'sale',
    askingPrice: 150000,
    method: 'both',
    meetupArea: '강남구',
    shippingFee: 3500,
    status: 'completed',
    completionSource: 'mutual',
    day: 2,
    hour: 14,
  },
  {
    id: 'listing-07',
    ownerId: 'user-minsu',
    title: '2022 양의지 팀컬러 카드',
    sport: 'baseball',
    player: '양의지',
    manufacturer: 'SCC',
    setName: 'Team Collection',
    year: '2022',
    cardNumber: '021',
    condition: 'near_mint',
    conditionNote: '네 모서리 모두 날카롭고 표면 인쇄도 고릅니다. 직사광선 없이 보관했습니다.',
    transactionType: 'sale',
    askingPrice: 45000,
    method: 'meetup',
    meetupArea: '송파구',
    shippingFee: null,
    day: 6,
    hour: 9,
  },
  {
    id: 'listing-08',
    ownerId: 'user-yujin',
    title: '2018 이대호 레전드 카드',
    sport: 'baseball',
    player: '이대호',
    manufacturer: 'Topps',
    setName: 'KBO Legends',
    year: '2018',
    cardNumber: '08',
    condition: 'good',
    conditionNote: '하단 모서리에 약한 사용감이 있고 나머지는 깨끗합니다. 교환 목적의 여분 카드입니다.',
    transactionType: 'trade',
    askingPrice: null,
    tradeWish: '박찬호나 선동열 빈티지 베이스 카드와 교환을 희망합니다.',
    method: 'both',
    meetupArea: '분당구',
    shippingFee: 3000,
    day: 4,
    hour: 11,
  },
  {
    id: 'listing-09',
    ownerId: 'user-court',
    title: '2003 르브론 제임스 루키 카드',
    sport: 'basketball',
    player: '르브론 제임스',
    manufacturer: 'Topps',
    setName: 'Chrome',
    year: '2003',
    cardNumber: '111',
    condition: 'near_mint',
    conditionNote: '슬랩 속 카드 모서리는 날카롭고 표면 광택이 살아 있습니다. 등급 숫자는 등록자가 케이스에서 옮긴 값입니다.',
    gradeStatus: 'graded',
    grader: 'BGS',
    grade: '9.5',
    certNumber: '0009123344',
    transactionType: 'sale',
    askingPrice: 320000,
    method: 'delivery',
    shippingFee: 4000,
    day: 6,
    hour: 16,
  },
  {
    id: 'listing-10',
    ownerId: 'user-court',
    title: '2021 스테판 커리 프리즘',
    sport: 'basketball',
    player: '스테판 커리',
    manufacturer: 'Panini',
    setName: 'Prizm',
    year: '2021',
    cardNumber: '1A',
    parallel: 'Silver',
    condition: 'near_mint',
    conditionNote: '실버 프리즘 표면 스크래치는 없고 센터링이 약간 오른쪽으로 기울었습니다.',
    transactionType: 'sale',
    askingPrice: 78000,
    method: 'both',
    meetupArea: '강남구',
    shippingFee: 3000,
    day: 5,
    hour: 13,
  },
  {
    id: 'listing-11',
    ownerId: 'user-court',
    title: '1997 코비 브라이언트 2년차',
    sport: 'basketball',
    player: '코비 브라이언트',
    manufacturer: 'Topps',
    setName: 'Chrome',
    year: '1997',
    cardNumber: '171',
    condition: 'good',
    conditionNote: '모서리 화이트닝이 조금 있고 표면은 대체로 균일합니다. 교환 조건을 문의에서 맞추고 있습니다.',
    transactionType: 'trade',
    askingPrice: null,
    tradeWish: '90년대 농구 루키나 같은 시기 코비 베이스와 교환하고 싶습니다.',
    method: 'delivery',
    shippingFee: 3500,
    status: 'reserved',
    day: 3,
    hour: 17,
  },
  {
    id: 'listing-12',
    ownerId: 'user-court',
    title: '2023 니콜라 요키치 프리즘',
    sport: 'basketball',
    player: '니콜라 요키치',
    manufacturer: 'Panini',
    setName: 'Prizm',
    year: '2023',
    cardNumber: '200',
    condition: 'near_mint',
    conditionNote: '네 모서리와 표면이 깨끗하고 프린트 라인도 고릅니다. 원터치 홀더에 있습니다.',
    transactionType: 'sale',
    askingPrice: 210000,
    method: 'delivery',
    shippingFee: null,
    day: 4,
    hour: 19,
  },
  {
    id: 'listing-13',
    ownerId: 'user-yujin',
    title: '2019 루카 돈치치 베이스 나눔',
    sport: 'basketball',
    player: '루카 돈치치',
    manufacturer: 'Panini',
    setName: 'Hoops',
    year: '2019',
    cardNumber: '268',
    condition: 'played',
    conditionNote: '가장자리 사용감과 약한 표면 기스가 있습니다. 여분이어서 나눔합니다.',
    transactionType: 'giveaway',
    askingPrice: 0,
    method: 'meetup',
    meetupArea: '분당구',
    shippingFee: null,
    day: 2,
    hour: 18,
  },
  {
    id: 'listing-14',
    ownerId: 'user-court',
    title: '2024 김선형 KBL 카드',
    sport: 'basketball',
    player: '김선형',
    manufacturer: 'KBL',
    setName: 'Official',
    year: '2024',
    cardNumber: '04',
    condition: 'near_mint',
    conditionNote: '국내 발매 카드로 모서리와 표면이 깨끗합니다. 사진에 나온 상태 그대로입니다.',
    transactionType: 'sale',
    askingPrice: 56000,
    method: 'both',
    meetupArea: '송파구',
    shippingFee: 3000,
    day: 6,
    hour: 8,
  },
  {
    id: 'listing-15',
    ownerId: 'user-goal',
    title: '2022 손흥민 프리즘 실버',
    sport: 'soccer',
    player: '손흥민',
    manufacturer: 'Panini',
    setName: 'Prizm',
    year: '2022',
    cardNumber: '7',
    parallel: 'Silver',
    condition: 'near_mint',
    conditionNote: '표면 홀로 스크래치는 없고 모서리도 날카롭습니다. 등급 라벨 숫자는 등록자 입력입니다.',
    gradeStatus: 'graded',
    grader: 'PSA',
    grade: '10',
    certNumber: '67221098',
    transactionType: 'sale',
    askingPrice: 410000,
    method: 'both',
    meetupArea: '마포구',
    shippingFee: 3500,
    day: 6,
    hour: 14,
  },
  {
    id: 'listing-16',
    ownerId: 'user-goal',
    title: '2010 리오넬 메시 베이스',
    sport: 'soccer',
    player: '리오넬 메시',
    manufacturer: 'Panini',
    setName: 'World Cup',
    year: '2010',
    cardNumber: '010',
    condition: 'good',
    conditionNote: '좌측 모서리에 작은 사용감이 있고 표면 광택은 남아 있습니다. 슬리브 보관입니다.',
    transactionType: 'sale',
    askingPrice: 275000,
    method: 'delivery',
    shippingFee: 4000,
    day: 5,
    hour: 10,
  },
  {
    id: 'listing-17',
    ownerId: 'user-goal',
    title: '2023 엘링 홀란드 프리즘',
    sport: 'soccer',
    player: '엘링 홀란드',
    manufacturer: 'Panini',
    setName: 'Prizm',
    year: '2023',
    cardNumber: '9',
    parallel: 'Blue',
    condition: 'near_mint',
    conditionNote: '블루 패러렐 표면이 깨끗하고 센터링이 약간 아래입니다. 교환용으로 올립니다.',
    transactionType: 'trade',
    askingPrice: null,
    tradeWish: '손흥민 프리즘이나 김민재 루키 카드와 교환하고 싶습니다.',
    method: 'meetup',
    meetupArea: '마포구',
    shippingFee: null,
    day: 4,
    hour: 16,
  },
  {
    id: 'listing-18',
    ownerId: 'user-goal',
    title: '2023 김민재 루키 카드',
    sport: 'soccer',
    player: '김민재',
    manufacturer: 'Topps',
    setName: 'Chrome',
    year: '2023',
    cardNumber: '15',
    condition: 'near_mint',
    conditionNote: '모서리와 표면이 깨끗합니다. 지인과 앱 밖에서 거래를 마쳐 외부 완료로 표시한 데모 매물입니다.',
    transactionType: 'sale',
    askingPrice: 89000,
    method: 'delivery',
    shippingFee: 3000,
    status: 'completed',
    completionSource: 'external',
    day: 1,
    hour: 13,
  },
  {
    id: 'listing-19',
    ownerId: 'user-yujin',
    title: '2001 타이거 우즈 어퍼덱',
    sport: 'other',
    player: '타이거 우즈',
    manufacturer: 'Upper Deck',
    setName: 'Golf',
    year: '2001',
    cardNumber: '1',
    condition: 'good',
    conditionNote: '가장자리에 약한 사용감이 있고 표면 포커스는 고릅니다. 골프 카드 여분입니다.',
    transactionType: 'sale',
    askingPrice: 120000,
    method: 'delivery',
    shippingFee: 3500,
    day: 3,
    hour: 12,
  },
  {
    id: 'listing-20',
    ownerId: 'user-yujin',
    title: '2018 로저 페더러 카드',
    sport: 'other',
    player: '로저 페더러',
    manufacturer: 'Topps',
    setName: 'Tennis',
    year: '2018',
    cardNumber: '20',
    condition: 'near_mint',
    conditionNote: '모서리 네 곳이 날카롭고 표면 기스는 보이지 않습니다. 테니스 기타 종목 카드입니다.',
    transactionType: 'sale',
    askingPrice: 64000,
    method: 'both',
    meetupArea: '분당구',
    shippingFee: 3000,
    day: 2,
    hour: 11,
  },
]

function toListing(draft: Draft): Listing {
  const createdAt = at(draft.day, draft.hour)
  return {
    id: draft.id,
    ownerId: draft.ownerId,
    title: draft.title,
    sport: draft.sport,
    player: draft.player,
    manufacturer: draft.manufacturer ?? null,
    setName: draft.setName ?? null,
    year: draft.year ?? null,
    cardNumber: draft.cardNumber ?? null,
    parallel: draft.parallel ?? null,
    condition: draft.condition,
    conditionNote: draft.conditionNote,
    gradeStatus: draft.gradeStatus ?? 'ungraded',
    grader: draft.grader ?? null,
    grade: draft.grade ?? null,
    certNumber: draft.certNumber ?? null,
    transactionType: draft.transactionType,
    askingPrice: draft.askingPrice,
    tradeWish: draft.tradeWish ?? null,
    method: draft.method,
    meetupArea: draft.meetupArea ?? null,
    shippingFee: draft.shippingFee,
    images: [
      placeholderImage(draft.sport, draft.player, '앞면'),
      placeholderImage(draft.sport, draft.player, '뒷면'),
    ],
    status: draft.status ?? 'available',
    visibility: 'visible',
    version: draft.status ? 2 : 1,
    completionSource: draft.completionSource ?? null,
    isDemo: true,
    createdAt,
    updatedAt: createdAt,
  }
}

function msg(id: string, inquiryId: string, senderId: string, body: string, day: number, hour: number, minute: number): Message {
  return {
    id,
    inquiryId,
    senderId,
    body,
    clientMessageId: `seed-${id}`,
    createdAt: at(day, hour, minute),
  }
}

export function createSeed(): AppState {
  const listings = drafts.map(toListing)
  const inquiries: Inquiry[] = [
    {
      id: 'inquiry-l02',
      listingId: 'listing-02',
      buyerId: 'user-minsu',
      sellerId: 'user-landers',
      buyerLastReadMessageId: 'm-l02-2',
      sellerLastReadMessageId: 'm-l02-2',
      createdAt: at(4, 16, 0),
    },
    {
      id: 'inquiry-l06',
      listingId: 'listing-06',
      buyerId: 'user-court',
      sellerId: 'user-landers',
      buyerLastReadMessageId: 'm-l06-2',
      sellerLastReadMessageId: 'm-l06-2',
      createdAt: at(2, 15, 0),
    },
    {
      id: 'inquiry-l11',
      listingId: 'listing-11',
      buyerId: 'user-goal',
      sellerId: 'user-court',
      buyerLastReadMessageId: 'm-l11-2',
      sellerLastReadMessageId: 'm-l11-2',
      createdAt: at(3, 18, 0),
    },
    {
      id: 'inquiry-l15',
      listingId: 'listing-15',
      buyerId: 'user-minsu',
      sellerId: 'user-goal',
      buyerLastReadMessageId: 'm-l15-1',
      sellerLastReadMessageId: 'm-l15-2',
      createdAt: at(6, 15, 0),
    },
    {
      id: 'inquiry-l09',
      listingId: 'listing-09',
      buyerId: 'user-yujin',
      sellerId: 'user-court',
      buyerLastReadMessageId: 'm-l09-1',
      sellerLastReadMessageId: 'm-l09-1',
      createdAt: at(6, 17, 0),
    },
    {
      id: 'inquiry-l03',
      listingId: 'listing-03',
      buyerId: 'user-goal',
      sellerId: 'user-minsu',
      buyerLastReadMessageId: 'm-l03-1',
      sellerLastReadMessageId: null,
      createdAt: at(5, 19, 0),
    },
  ]
  const messages: Message[] = [
    msg('m-l02-1', 'inquiry-l02', 'user-minsu', '류현진 카드 배송으로 문의드립니다. 상태 사진 기준으로 모서리만 확인하면 될까요?', 4, 16, 2),
    msg('m-l02-2', 'inquiry-l02', 'user-landers', '네. 좌상단만 살짝 있고 나머지는 설명과 같습니다. 이 문의를 예약으로 잡아 두었습니다.', 4, 16, 20),
    msg('m-l06-1', 'inquiry-l06', 'user-court', '박찬호 카드 실물 상태 확인하고 직거래로 진행했습니다.', 2, 15, 10),
    msg('m-l06-2', 'inquiry-l06', 'user-landers', '수령 확인 감사합니다. 완료 요청 드렸고 상대 확인까지 끝난 기록입니다.', 2, 16, 0),
    msg('m-l11-1', 'inquiry-l11', 'user-goal', '코비 카드, 손흥민 베이스와 교환 가능할까요?', 3, 18, 5),
    msg('m-l11-2', 'inquiry-l11', 'user-court', '조건 맞습니다. 예약해 두었고 실물 교환 뒤 완료 요청을 보냈습니다.', 3, 18, 40),
    msg('m-l15-1', 'inquiry-l15', 'user-minsu', '손흥민 프리즘 직거래 가능 시간 있을까요? 주말 마포 쪽을 생각하고 있습니다.', 6, 15, 10),
    msg('m-l15-2', 'inquiry-l15', 'user-goal', '토요일 오후 가능합니다. 희망 가격은 등록한 금액이고, 상태는 사진과 같습니다.', 6, 15, 30),
    msg('m-l09-1', 'inquiry-l09', 'user-yujin', '르브론 카드 배송비 포함 여부를 여쭙니다. 등급 숫자는 등록자 입력이라고 이해했습니다.', 6, 17, 5),
    msg('m-l03-1', 'inquiry-l03', 'user-goal', '김하성 리프랙터, 손흥민 베이스와 교환 이야기 나누고 싶습니다.', 5, 19, 10),
  ]
  const trades: Trade[] = [
    {
      id: 'trade-l02',
      listingId: 'listing-02',
      inquiryId: 'inquiry-l02',
      sellerId: 'user-landers',
      buyerId: 'user-minsu',
      status: 'reserved',
      snapshot: { title: '2019 류현진 올스타 카드', transactionType: 'sale', askingPrice: 92000, proposedPrice: null },
      agreedPrice: null,
      createdAt: at(4, 16, 25),
      updatedAt: at(4, 16, 25),
    },
    {
      id: 'trade-l06',
      listingId: 'listing-06',
      inquiryId: 'inquiry-l06',
      sellerId: 'user-landers',
      buyerId: 'user-court',
      status: 'confirmed',
      snapshot: { title: '1998 박찬호 플레어 카드', transactionType: 'sale', askingPrice: 150000, proposedPrice: 140000 },
      agreedPrice: 140000,
      createdAt: at(2, 15, 30),
      updatedAt: at(2, 16, 20),
    },
    {
      id: 'trade-l11',
      listingId: 'listing-11',
      inquiryId: 'inquiry-l11',
      sellerId: 'user-court',
      buyerId: 'user-goal',
      status: 'completion_requested',
      snapshot: { title: '1997 코비 브라이언트 2년차', transactionType: 'trade', askingPrice: null, proposedPrice: null },
      agreedPrice: null,
      createdAt: at(3, 18, 45),
      updatedAt: at(3, 19, 10),
    },
  ]
  const favorites: Favorite[] = [
    { userId: 'user-minsu', listingId: 'listing-01', createdAt: at(6, 11, 30) },
    { userId: 'user-minsu', listingId: 'listing-15', createdAt: at(6, 14, 20) },
    { userId: 'user-minsu', listingId: 'listing-09', createdAt: at(6, 16, 10) },
    { userId: 'user-landers', listingId: 'listing-15', createdAt: at(6, 14, 40) },
    { userId: 'user-court', listingId: 'listing-01', createdAt: at(6, 12, 0) },
  ]
  return {
    schemaVersion: 1,
    currentUserId: 'user-minsu',
    users: demoUsers,
    listings,
    favorites,
    inquiries,
    messages,
    trades,
    reports: [],
  }
}
